### ISSUE TITLE
H2O install problem: Found version 3.18.0.11, but running version 3.28.0.4

### ISSUE THREAD

**Issue by JasonRafeMiller** [bgudenas/DeepLncRNA#4]
Could you update the instructions on how to install DeepLncRNA? As written, they install a newer version of H2O that DeepLncRNA cannot use. I provide a work-around below but perhaps you know of a better way. 

During installation, all the commands work until the 3rd from last. After that fails, the last two commands don't work either. The command that fails is "preds = DeepLncRNA(df, df$ensembl_transcript_id)". That command successfully starts a local H2O server that does respond on localhost. The H2O web site is running version 3.28.0.4, which seems to be the latest from H20. The DeepLncRNA code, however, "was built using h2o version h2o_3.18.0.11" as it says in the README. The H2O client code seems to throw an exception if the client version is behind the server version.

Googling for the old version number, I found this command which looked promising: install.packages("https://cran.r-project.org/src/contrib/Archive/h2o/h2o_3.18.0.11.tar.gz", repos=NULL, type="source") . 

That command did the trick. The rest of the commands on the DeepLncRNA README executed correctly. The only problem was this warning:

Warning message:
In h2o.clusterInfo() : 
Your H2O cluster version is too old (1 year, 9 months and 23 days)!
Please download and install the latest version from http://h2o.ai/download/

Finally, I received the following predictions, which I hope are expected. 

> preds 
                predict   Cytosol   Nuclear            gene
ENST00000440955 Nuclear 0.3564160 0.6435840 ENSG00000224294
ENST00000613231 Cytosol 0.8248627 0.1751373 ENSG00000278709
ENST00000614771 Cytosol 0.7054763 0.2945237 ENSG00000278709**

**Comment by bgudenas** [comment]
Hi Jason,

Yes, you are correct. DeepLncRNA was built using "h2o_3.18.0.11" and therefore will only run if you install that arhived version. This was an unintended and unfortunate side effect of using H2O, which i did not realize until after the project had been completed. I've have heard that H2O has  recently fixed this issue therefore i should just retrain the model with a new version.

Until then, i will update the readme to be more descriptive of this issue.

Best,
Brian
